"""Typed research-agent contracts and model-provider interfaces."""

from company_lens.agent.model import (
    ModelMessage,
    ModelProviderError,
    ModelPurpose,
    ModelUsage,
    ResearchModelProvider,
    StructuredModelResult,
    TextModelResult,
)
from company_lens.agent.openai_provider import (
    OpenAIResearchModelProvider,
    build_openai_model_provider,
)
from company_lens.agent.schemas import (
    AgentCapability,
    AgentError,
    AgentErrorCategory,
    AgentErrorSeverity,
    AgentRunStatus,
    AgentState,
    CalculationBranch,
    ChartBranch,
    CitationReference,
    DocumentRetrievalBranch,
    EvidenceEnvelope,
    ExecutionPlan,
    ExecutionPolicy,
    FinancialFactsBranch,
    MacroSeriesBranch,
    QuestionAnalysis,
    ResearchRoute,
    SessionMessage,
    TrajectoryEvent,
)

__all__ = [
    "AgentCapability",
    "AgentError",
    "AgentErrorCategory",
    "AgentErrorSeverity",
    "AgentRunStatus",
    "AgentState",
    "CalculationBranch",
    "ChartBranch",
    "CitationReference",
    "DocumentRetrievalBranch",
    "EvidenceEnvelope",
    "ExecutionPlan",
    "ExecutionPolicy",
    "FinancialFactsBranch",
    "MacroSeriesBranch",
    "ModelMessage",
    "ModelProviderError",
    "ModelPurpose",
    "ModelUsage",
    "OpenAIResearchModelProvider",
    "QuestionAnalysis",
    "ResearchModelProvider",
    "ResearchRoute",
    "SessionMessage",
    "StructuredModelResult",
    "TextModelResult",
    "TrajectoryEvent",
    "build_openai_model_provider",
]
