"""Typed research-agent contracts and model-provider interfaces."""

from company_lens.agent.model import (
    ModelMessage,
    ModelProviderError,
    ModelPurpose,
    ModelUsage,
    ResearchModelProvider,
    StructuredModelResult,
    TextModelResult,
)
from company_lens.agent.openai_provider import (
    OpenAIResearchModelProvider,
    build_openai_model_provider,
)
from company_lens.agent.schemas import (
    AgentCapability,
    AgentError,
    AgentErrorCategory,
    AgentErrorSeverity,
    AgentRunStatus,
    AgentState,
    AnswerValidation,
    BranchOutcome,
    BranchStatus,
    CalculationBranch,
    CalculationBranchResult,
    ChartBranch,
    CitationReference,
    DocumentRetrievalBranch,
    EvidenceEnvelope,
    ExecutionPlan,
    ExecutionPolicy,
    FinancialBranchResult,
    FinancialFactsBranch,
    MacroBranchResult,
    MacroSeriesBranch,
    QuestionAnalysis,
    ResearchRoute,
    SessionMessage,
    TrajectoryEvent,
)
from company_lens.agent.tools import ResearchToolError, ResearchTools, SqlResearchTools
from company_lens.agent.workflow import (
    ResearchAgent,
    ResearchAgentRuntime,
    build_research_graph,
    create_initial_agent_state,
)

__all__ = [
    "AgentCapability",
    "AgentError",
    "AgentErrorCategory",
    "AgentErrorSeverity",
    "AgentRunStatus",
    "AgentState",
    "AnswerValidation",
    "BranchOutcome",
    "BranchStatus",
    "CalculationBranch",
    "CalculationBranchResult",
    "ChartBranch",
    "CitationReference",
    "DocumentRetrievalBranch",
    "EvidenceEnvelope",
    "ExecutionPlan",
    "ExecutionPolicy",
    "FinancialFactsBranch",
    "FinancialBranchResult",
    "MacroBranchResult",
    "MacroSeriesBranch",
    "ModelMessage",
    "ModelProviderError",
    "ModelPurpose",
    "ModelUsage",
    "OpenAIResearchModelProvider",
    "QuestionAnalysis",
    "ResearchModelProvider",
    "ResearchAgent",
    "ResearchAgentRuntime",
    "ResearchRoute",
    "ResearchToolError",
    "ResearchTools",
    "SessionMessage",
    "StructuredModelResult",
    "TextModelResult",
    "TrajectoryEvent",
    "SqlResearchTools",
    "build_openai_model_provider",
    "build_research_graph",
    "create_initial_agent_state",
]
