/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Companies */
        get: operations["companies_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Runs */
        get: operations["list_research_runs_api_v1_research_get"];
        put?: never;
        /** Start Research */
        post: operations["start_research_api_v1_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research */
        get: operations["get_research_api_v1_research__run_id__get"];
        put?: never;
        post?: never;
        /** Cancel Research */
        delete: operations["cancel_research_api_v1_research__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_v1_research__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/{run_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sources */
        get: operations["get_sources_api_v1_research__run_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentError */
        AgentError: {
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            category: components["schemas"]["AgentErrorCategory"];
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Node */
            node?: string | null;
            severity: components["schemas"]["AgentErrorSeverity"];
        };
        /**
         * AgentErrorCategory
         * @enum {string}
         */
        AgentErrorCategory: "validation" | "provider_timeout" | "provider_rate_limit" | "provider_connection" | "provider_auth" | "provider_service" | "provider_refusal" | "provider_response" | "tool" | "budget" | "internal";
        /**
         * AgentErrorSeverity
         * @enum {string}
         */
        AgentErrorSeverity: "recoverable" | "terminal";
        /**
         * AgentRunStatus
         * @enum {string}
         */
        AgentRunStatus: "pending" | "running" | "completed" | "partial" | "abstained" | "failed";
        /** BranchOutcome */
        BranchOutcome: {
            /** Attempts */
            attempts: number;
            /** Branch Id */
            branch_id: string;
            error?: components["schemas"]["AgentError"] | null;
            /** Kind */
            kind: string;
            /**
             * Optional
             * @default false
             */
            optional: boolean;
            status: components["schemas"]["BranchStatus"];
        };
        /**
         * BranchStatus
         * @enum {string}
         */
        BranchStatus: "completed" | "failed" | "skipped";
        /** ChartPoint */
        ChartPoint: {
            /** Source Urls */
            source_urls: string[];
            /** Values */
            values: {
                [key: string]: string;
            };
            /**
             * X
             * Format: date
             */
            x: string;
        };
        /** ChartSeries */
        ChartSeries: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
        };
        /** ChartSpecification */
        ChartSpecification: {
            /** Chart Type */
            chart_type: string;
            /** Data */
            data: components["schemas"]["ChartPoint"][];
            /**
             * Schema Version
             * @default company-lens.chart.v1
             */
            schema_version: string;
            /** Series */
            series: components["schemas"]["ChartSeries"][];
            /** Sources */
            sources: string[];
            /** Title */
            title: string;
            /** X Label */
            x_label: string;
        };
        /** CompaniesResponse */
        CompaniesResponse: {
            /** Items */
            items: components["schemas"]["CompanyOutput"][];
            /** Total */
            total: number;
        };
        /** CompanyOutput */
        CompanyOutput: {
            /** Cik */
            cik?: string | null;
            /** Display Name */
            display_name: string;
            /** Exchange */
            exchange?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Legal Name */
            legal_name: string;
            /** Primary Ticker */
            primary_ticker?: string | null;
        };
        /** ComponentHealth */
        ComponentHealth: {
            /** Detail */
            detail?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /**
         * EvidenceKind
         * @enum {string}
         */
        EvidenceKind: "document" | "financial_fact" | "macro_observation" | "calculation";
        /** ExecutionPolicy */
        ExecutionPolicy: {
            /**
             * Max Repair Attempts
             * @default 1
             */
            max_repair_attempts: number;
            /**
             * Max Retries Per Node
             * @default 2
             */
            max_retries_per_node: number;
            /**
             * Max Tool Calls
             * @default 10
             */
            max_tool_calls: number;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Actor Id */
            actor_id?: string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Rating
             * @enum {string}
             */
            rating: "positive" | "negative";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Feedback Id
             * Format: uuid
             */
            feedback_id: string;
            /**
             * Rating
             * @enum {string}
             */
            rating: "positive" | "negative";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Correlation Id */
            correlation_id: string | null;
            database: components["schemas"]["ComponentHealth"];
            /** Environment */
            environment: string;
            /** Service */
            service: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /** PublicErrorDetail */
        PublicErrorDetail: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Message */
            message: string;
        };
        /** PublicErrorResponse */
        PublicErrorResponse: {
            error: components["schemas"]["PublicErrorDetail"];
        };
        /** ResearchAccepted */
        ResearchAccepted: {
            /** Events Url */
            events_url: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Run Url */
            run_url: string;
            /** Session Id */
            session_id: string;
            /** Sources Url */
            sources_url: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /** ResearchCitationOutput */
        ResearchCitationOutput: {
            /**
             * Claim Ids
             * @default []
             */
            claim_ids: string[];
            /** Evidence Id */
            evidence_id: string;
            kind: components["schemas"]["EvidenceKind"];
            /** Label */
            label: string;
            /** Lineage Refs */
            lineage_refs: string[];
            /** Source Urls */
            source_urls: string[];
            /** Summary */
            summary: string;
        };
        /** ResearchExecutionOutput */
        ResearchExecutionOutput: {
            /** Branches */
            branches: components["schemas"]["BranchOutcome"][];
            /** Errors */
            errors: components["schemas"]["AgentError"][];
            /** Repair Attempts */
            repair_attempts: number;
            /** Tool Calls Used */
            tool_calls_used: number;
            /**
             * Trajectory
             * @default []
             */
            trajectory: components["schemas"]["TrajectoryEvent"][];
        };
        /** ResearchResult */
        ResearchResult: {
            agent_status: components["schemas"]["AgentRunStatus"];
            /** Answer */
            answer?: string | null;
            chart?: components["schemas"]["ChartSpecification"] | null;
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["ResearchCitationOutput"][];
            execution: components["schemas"]["ResearchExecutionOutput"];
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["SourcePreview"][];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["AgentError"][];
        };
        /** ResearchRunListResponse */
        ResearchRunListResponse: {
            /** Items */
            items: components["schemas"]["ResearchRunResponse"][];
            /** Total */
            total: number;
        };
        /** ResearchRunResponse */
        ResearchRunResponse: {
            /** Cancellation Requested At */
            cancellation_requested_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Deadline At
             * Format: date-time
             */
            deadline_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Question */
            question: string;
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            result?: components["schemas"]["ResearchResult"] | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Session Id */
            session_id: string;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["ResearchRunStatus"];
        };
        /**
         * ResearchRunStatus
         * @enum {string}
         */
        ResearchRunStatus: "queued" | "running" | "cancellation_requested" | "completed" | "partial" | "abstained" | "failed" | "cancelled" | "timed_out";
        /** ResearchSourcesResponse */
        ResearchSourcesResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["SourcePreview"][];
        };
        /** SourcePreview */
        SourcePreview: {
            /** Evidence Id */
            evidence_id: string;
            /** Exact Url */
            exact_url: string;
            kind: components["schemas"]["EvidenceKind"];
            /** Page End */
            page_end?: number | null;
            /** Page Start */
            page_start?: number | null;
            /** Section Id */
            section_id?: string | null;
            /** Source Url */
            source_url: string;
            status: components["schemas"]["SourceStatus"];
            /** Title */
            title: string;
        };
        /**
         * SourceStatus
         * @enum {string}
         */
        SourceStatus: "available" | "inaccessible" | "invalid" | "unchecked";
        /** StartResearchRequest */
        StartResearchRequest: {
            policy?: components["schemas"]["ExecutionPolicy"];
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** TrajectoryEvent */
        TrajectoryEvent: {
            /** Details */
            details?: {
                [key: string]: string | number | boolean | null;
            };
            /** Duration Ms */
            duration_ms?: number | null;
            /** Node */
            node: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            status: components["schemas"]["TrajectoryStatus"];
            /** Summary */
            summary: string;
        };
        /**
         * TrajectoryStatus
         * @enum {string}
         */
        TrajectoryStatus: "started" | "completed" | "failed" | "skipped";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    companies_api_v1_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompaniesResponse"];
                };
            };
        };
    };
    feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_research_runs_api_v1_research_get: {
        parameters: {
            query: {
                session_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_research_api_v1_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchAccepted"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicErrorResponse"];
                };
            };
        };
    };
    get_research_api_v1_research__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_research_api_v1_research__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_research__run_id__events_get: {
        parameters: {
            query?: {
                after_id?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned research execution event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sources_api_v1_research__run_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
